In [1]:
import numpy as np
import pandas as pd

In [3]:
import matplotlib.pyplot as plt
import seaborn as sns

plt.style.use('fivethirtyeight')
pd.set_option('display.max_columns', 26)

In [4]:
# upload dataset to colab
from google.colab import files
uploaded = files.upload()

Saving kidney_disease.csv to kidney_disease.csv


In [36]:
# read dataset to pandas dataframe
import io

df = pd.read_csv(io.BytesIO(uploaded['kidney_disease.csv']))
df.head()

id   age    bp     sg   al   su     rbc        pc         pcc          ba  \
0   0  48.0  80.0  1.020  1.0  0.0     NaN    normal  notpresent  notpresent   
1   1   7.0  50.0  1.020  4.0  0.0     NaN    normal  notpresent  notpresent   
2   2  62.0  80.0  1.010  2.0  3.0  normal    normal  notpresent  notpresent   
3   3  48.0  70.0  1.005  4.0  0.0  normal  abnormal     present  notpresent   
4   4  51.0  80.0  1.010  2.0  0.0  normal    normal  notpresent  notpresent   

     bgr    bu   sc    sod  pot  hemo pcv    wc   rc  htn   dm cad appet   pe  \
0  121.0  36.0  1.2    NaN  NaN  15.4  44  7800  5.2  yes  yes  no  good   no   
1    NaN  18.0  0.8    NaN  NaN  11.3  38  6000  NaN   no   no  no  good   no   
2  423.0  53.0  1.8    NaN  NaN   9.6  31  7500  NaN   no  yes  no  poor   no   
3  117.0  56.0  3.8  111.0  2.5  11.2  32  6700  3.9  yes   no  no  poor  yes   
4  106.0  26.0  1.4    NaN  NaN  11.6  35  7300  4.6   no   no  no  good   no   

   ane classification  
0   no            ckd  
1   no            ckd  
2  yes            ckd  
3  yes            ckd  
4   no            ckd

In [37]:
# Remove uneeded id column
df.drop('id', axis = 1, inplace = True)

In [38]:
df.head()

age    bp     sg   al   su     rbc        pc         pcc          ba  \
0  48.0  80.0  1.020  1.0  0.0     NaN    normal  notpresent  notpresent   
1   7.0  50.0  1.020  4.0  0.0     NaN    normal  notpresent  notpresent   
2  62.0  80.0  1.010  2.0  3.0  normal    normal  notpresent  notpresent   
3  48.0  70.0  1.005  4.0  0.0  normal  abnormal     present  notpresent   
4  51.0  80.0  1.010  2.0  0.0  normal    normal  notpresent  notpresent   

     bgr    bu   sc    sod  pot  hemo pcv    wc   rc  htn   dm cad appet   pe  \
0  121.0  36.0  1.2    NaN  NaN  15.4  44  7800  5.2  yes  yes  no  good   no   
1    NaN  18.0  0.8    NaN  NaN  11.3  38  6000  NaN   no   no  no  good   no   
2  423.0  53.0  1.8    NaN  NaN   9.6  31  7500  NaN   no  yes  no  poor   no   
3  117.0  56.0  3.8  111.0  2.5  11.2  32  6700  3.9  yes   no  no  poor  yes   
4  106.0  26.0  1.4    NaN  NaN  11.6  35  7300  4.6   no   no  no  good   no   

   ane classification  
0   no            ckd  
1   no            ckd  
2  yes            ckd  
3  yes            ckd  
4   no            ckd

In [39]:
# View data info
df.info()     # Some are numbers some are objects

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 400 entries, 0 to 399
Data columns (total 25 columns):
 #   Column          Non-Null Count  Dtype  
---  ------          --------------  -----  
 0   age             391 non-null    float64
 1   bp              388 non-null    float64
 2   sg              353 non-null    float64
 3   al              354 non-null    float64
 4   su              351 non-null    float64
 5   rbc             248 non-null    object 
 6   pc              335 non-null    object 
 7   pcc             396 non-null    object 
 8   ba              396 non-null    object 
 9   bgr             356 non-null    float64
 10  bu              381 non-null    float64
 11  sc              383 non-null    float64
 12  sod             313 non-null    float64
 13  pot             312 non-null    float64
 14  hemo            348 non-null    float64
 15  pcv             330 non-null    object 
 16  wc              295 non-null    object 
 17  rc              270 non-null    obj

In [40]:
# Some of the data are objects, although they are numeric in dataset. Convert them to numeric
df['pcv'] = pd.to_numeric(df['pcv'], errors = 'coerce')
df['wc'] = pd.to_numeric(df['wc'], errors = 'coerce')
df['rc'] = pd.to_numeric(df['rc'], errors = 'coerce')

In [41]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 400 entries, 0 to 399
Data columns (total 25 columns):
 #   Column          Non-Null Count  Dtype  
---  ------          --------------  -----  
 0   age             391 non-null    float64
 1   bp              388 non-null    float64
 2   sg              353 non-null    float64
 3   al              354 non-null    float64
 4   su              351 non-null    float64
 5   rbc             248 non-null    object 
 6   pc              335 non-null    object 
 7   pcc             396 non-null    object 
 8   ba              396 non-null    object 
 9   bgr             356 non-null    float64
 10  bu              381 non-null    float64
 11  sc              383 non-null    float64
 12  sod             313 non-null    float64
 13  pot             312 non-null    float64
 14  hemo            348 non-null    float64
 15  pcv             329 non-null    float64
 16  wc              294 non-null    float64
 17  rc              269 non-null    flo

In [42]:
# Separate numeric and categorical (object) data
num_columns = [col for col in df.columns if df[col].dtype != 'object']
cat_columns = [col for col in df.columns if df[col].dtype == 'object']

In [43]:
num_columns

['age',
 'bp',
 'sg',
 'al',
 'su',
 'bgr',
 'bu',
 'sc',
 'sod',
 'pot',
 'hemo',
 'pcv',
 'wc',
 'rc']

In [44]:
cat_columns

['rbc',
 'pc',
 'pcc',
 'ba',
 'htn',
 'dm',
 'cad',
 'appet',
 'pe',
 'ane',
 'classification']

In [45]:
# Check available values of each category column
for col in cat_columns:
    print(f"{col} has {df[col].unique()} values\n")

rbc has [nan 'normal' 'abnormal'] values

pc has ['normal' 'abnormal' nan] values

pcc has ['notpresent' 'present' nan] values

ba has ['notpresent' 'present' nan] values

htn has ['yes' 'no' nan] values

dm has ['yes' 'no' ' yes' '\tno' '\tyes' nan] values

cad has ['no' 'yes' '\tno' nan] values

appet has ['good' 'poor' nan] values

pe has ['no' 'yes' nan] values

ane has ['no' 'yes' nan] values

classification has ['ckd' 'ckd\t' 'notckd'] values



In [46]:
# Some columns need to be fixed (ex: '\tno' needs to be replaced with 'no')
df['dm'].replace(to_replace = {'\tno' :'no' ,'\tyes' :'yes' , ' yes' :'yes'}, inplace = True)
df['cad'].replace(to_replace = '\tno' , value = 'no', inplace = True)
df['classification'].replace(to_replace = "ckd\t" , value =" ckd", inplace = True) 

In [47]:
for col in cat_columns:
    print(f"{col} has {df[col].unique()} values\n")

rbc has [nan 'normal' 'abnormal'] values

pc has ['normal' 'abnormal' nan] values

pcc has ['notpresent' 'present' nan] values

ba has ['notpresent' 'present' nan] values

htn has ['yes' 'no' nan] values

dm has ['yes' 'no' nan] values

cad has ['no' 'yes' nan] values

appet has ['good' 'poor' nan] values

pe has ['no' 'yes' nan] values

ane has ['no' 'yes' nan] values

classification has ['ckd' ' ckd' 'notckd'] values



In [48]:
# Some columns have null values, therefore we will imputate these values (populate)
df.isna().sum()

age                 9
bp                 12
sg                 47
al                 46
su                 49
rbc               152
pc                 65
pcc                 4
ba                  4
bgr                44
bu                 19
sc                 17
sod                87
pot                88
hemo               52
pcv                71
wc                106
rc                131
htn                 2
dm                  2
cad                 2
appet               1
pe                  1
ane                 1
classification      0
dtype: int64

In [49]:
df[num_columns].isnull().sum()

age       9
bp       12
sg       47
al       46
su       49
bgr      44
bu       19
sc       17
sod      87
pot      88
hemo     52
pcv      71
wc      106
rc      131
dtype: int64

In [50]:
df[cat_columns].isnull().sum()

rbc               152
pc                 65
pcc                 4
ba                  4
htn                 2
dm                  2
cad                 2
appet               1
pe                  1
ane                 1
classification      0
dtype: int64

In [51]:
# Random sampling for higher null values and mean/mode sampling for lower null values
def random_sample(feature):
    random_sample = df[feature].dropna().sample(df[feature].isna().sum())
    random_sample.index = df[df[feature].isnull()].index
    df.loc[df[feature].isnull(),feature] = random_sample
    
def impute_method(feature):
    frequent_feature = df[feature].mode()[0]
    df[feature] = df[feature].fillna(frequent_feature)

In [52]:
# Fill numeric columns using random sampling
for col in num_columns:
    random_sample(col)

In [53]:
df[num_columns].isnull().sum()

age     0
bp      0
sg      0
al      0
su      0
bgr     0
bu      0
sc      0
sod     0
pot     0
hemo    0
pcv     0
wc      0
rc      0
dtype: int64

In [54]:
# Random sampling for rbc and pc (greater null values)
random_sample('rbc')
random_sample('pc')

# mean/mode sampling for lower null values
for col in cat_columns:
    impute_method(col)

In [55]:
df[cat_columns].isnull().sum()

rbc               0
pc                0
pcc               0
ba                0
htn               0
dm                0
cad               0
appet             0
pe                0
ane               0
classification    0
dtype: int64

In [57]:
# Convert categorical data into labels of 1 and 0
from sklearn.preprocessing import LabelEncoder

encoder = LabelEncoder()
for col in cat_columns:
  df[col] = encoder.fit_transform(df[col])

In [58]:
df.head()

age    bp     sg   al   su  rbc  pc  pcc  ba    bgr    bu   sc    sod  \
0  48.0  80.0  1.020  1.0  0.0    1   1    0   0  121.0  36.0  1.2    4.5   
1   7.0  50.0  1.020  4.0  0.0    1   1    0   0  114.0  18.0  0.8  146.0   
2  62.0  80.0  1.010  2.0  3.0    1   1    0   0  423.0  53.0  1.8  140.0   
3  48.0  70.0  1.005  4.0  0.0    1   0    1   0  117.0  56.0  3.8  111.0   
4  51.0  80.0  1.010  2.0  0.0    1   1    0   0  106.0  26.0  1.4  138.0   

   pot  hemo   pcv      wc   rc  htn  dm  cad  appet  pe  ane  classification  
0  3.6  15.4  44.0  7800.0  5.2    1   1    0      0   0    0               1  
1  4.0  11.3  38.0  6000.0  5.8    0   0    0      0   0    0               1  
2  4.7   9.6  31.0  7500.0  2.8    0   1    0      1   0    1               1  
3  2.5  11.2  32.0  6700.0  3.9    1   0    0      1   1    1               1  
4  4.7  11.6  35.0  7300.0  4.6    0   0    0      0   0    0               1

In [59]:
# Split data
X = df.drop(columns = 'classification', axis = 1)
Y = df['classification']

In [60]:
X

age    bp     sg   al   su  rbc  pc  pcc  ba    bgr    bu   sc    sod  \
0    48.0  80.0  1.020  1.0  0.0    1   1    0   0  121.0  36.0  1.2    4.5   
1     7.0  50.0  1.020  4.0  0.0    1   1    0   0  114.0  18.0  0.8  146.0   
2    62.0  80.0  1.010  2.0  3.0    1   1    0   0  423.0  53.0  1.8  140.0   
3    48.0  70.0  1.005  4.0  0.0    1   0    1   0  117.0  56.0  3.8  111.0   
4    51.0  80.0  1.010  2.0  0.0    1   1    0   0  106.0  26.0  1.4  138.0   
..    ...   ...    ...  ...  ...  ...  ..  ...  ..    ...   ...  ...    ...   
395  55.0  80.0  1.020  0.0  0.0    1   1    0   0  140.0  49.0  0.5  150.0   
396  42.0  70.0  1.025  0.0  0.0    1   1    0   0   75.0  31.0  1.2  141.0   
397  12.0  80.0  1.020  0.0  0.0    1   1    0   0  100.0  26.0  0.6  137.0   
398  17.0  60.0  1.025  0.0  0.0    1   1    0   0  114.0  50.0  1.0  135.0   
399  58.0  80.0  1.025  0.0  0.0    1   1    0   0  131.0  18.0  1.1  141.0   

     pot  hemo   pcv      wc   rc  htn  dm  cad  appet  pe  ane  
0    3.6  15.4  44.0  7800.0  5.2    1   1    0      0   0    0  
1    4.0  11.3  38.0  6000.0  5.8    0   0    0      0   0    0  
2    4.7   9.6  31.0  7500.0  2.8    0   1    0      1   0    1  
3    2.5  11.2  32.0  6700.0  3.9    1   0    0      1   1    1  
4    4.7  11.6  35.0  7300.0  4.6    0   0    0      0   0    0  
..   ...   ...   ...     ...  ...  ...  ..  ...    ...  ..  ...  
395  4.9  15.7  47.0  6700.0  4.9    0   0    0      0   0    0  
396  3.5  16.5  54.0  7800.0  6.2    0   0    0      0   0    0  
397  4.4  15.8  49.0  6600.0  5.4    0   0    0      0   0    0  
398  4.9  14.2  51.0  7200.0  5.9    0   0    0      0   0    0  
399  3.5  15.8  53.0  6800.0  6.1    0   0    0      0   0    0  

[400 rows x 24 columns]

In [61]:
# feature selection - take only columns that have an effect
from sklearn.linear_model import Lasso
from sklearn.feature_selection import SelectFromModel

feture_el_model  = SelectFromModel(Lasso(alpha=0.005 ,random_state =42))

feture_el_model.fit(X, Y)
feture_el_model.get_support()

array([ True,  True, False,  True,  True,  True, False, False, False,
        True,  True,  True,  True, False,  True,  True, False,  True,
        True,  True,  True,  True, False,  True])

In [62]:
cols = X.columns
selected_feature = cols[feture_el_model.get_support()]

In [63]:
Xg = X[selected_feature]

In [64]:
Xg

age    bp   al   su  rbc    bgr    bu   sc    sod  hemo   pcv   rc  htn  \
0    48.0  80.0  1.0  0.0    1  121.0  36.0  1.2    4.5  15.4  44.0  5.2    1   
1     7.0  50.0  4.0  0.0    1  114.0  18.0  0.8  146.0  11.3  38.0  5.8    0   
2    62.0  80.0  2.0  3.0    1  423.0  53.0  1.8  140.0   9.6  31.0  2.8    0   
3    48.0  70.0  4.0  0.0    1  117.0  56.0  3.8  111.0  11.2  32.0  3.9    1   
4    51.0  80.0  2.0  0.0    1  106.0  26.0  1.4  138.0  11.6  35.0  4.6    0   
..    ...   ...  ...  ...  ...    ...   ...  ...    ...   ...   ...  ...  ...   
395  55.0  80.0  0.0  0.0    1  140.0  49.0  0.5  150.0  15.7  47.0  4.9    0   
396  42.0  70.0  0.0  0.0    1   75.0  31.0  1.2  141.0  16.5  54.0  6.2    0   
397  12.0  80.0  0.0  0.0    1  100.0  26.0  0.6  137.0  15.8  49.0  5.4    0   
398  17.0  60.0  0.0  0.0    1  114.0  50.0  1.0  135.0  14.2  51.0  5.9    0   
399  58.0  80.0  0.0  0.0    1  131.0  18.0  1.1  141.0  15.8  53.0  6.1    0   

     dm  cad  appet  ane  
0     1    0      0    0  
1     0    0      0    0  
2     1    0      1    1  
3     0    0      1    1  
4     0    0      0    0  
..   ..  ...    ...  ...  
395   0    0      0    0  
396   0    0      0    0  
397   0    0      0    0  
398   0    0      0    0  
399   0    0      0    0  

[400 rows x 17 columns]

In [65]:
# Split data into train and test
from sklearn.model_selection import train_test_split

x_train , x_test , y_train , y_test = train_test_split(Xg, Y, test_size = .3, random_state = 42)

In [66]:
# Create multiple models to obtain best model

from sklearn.naive_bayes import GaussianNB
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import confusion_matrix, accuracy_score

models = []
models.append(('LogisticRegression',LogisticRegression(solver='liblinear')))
models.append(('Naive bayes' ,GaussianNB()))
models.append(('Random Forest' ,RandomForestClassifier()))
models.append(('Decision Tree' ,DecisionTreeClassifier()))
models.append (('KNN' ,KNeighborsClassifier()))

In [67]:
for name, model in models:
    model.fit(x_train, y_train)
    prediction = model.predict(x_test)
    print(name)
    print(confusion_matrix(prediction, y_test))
    print(accuracy_score(prediction,y_test))
    print('\n')

LogisticRegression
[[70  0]
 [ 6 44]]
0.95


Naive bayes
[[71  3]
 [ 5 41]]
0.9333333333333333


RandomForest
[[76  0]
 [ 0 44]]
1.0


Decision Tree
[[ 0  4  0]
 [ 0 71  0]
 [ 0  1 44]]
0.9583333333333334


KNN
[[59  0]
 [17 44]]
0.8583333333333333




In [69]:
model = models[2][1]
prediction = model.predict(x_test)   
print('Random Forest')
print(confusion_matrix(prediction, y_test))
print(accuracy_score(prediction, y_test))
print('\n')

Random Forest
[[76  0]
 [ 0 44]]
1.0




In [70]:
# Save random forest model
import pickle
with open("Best-Model-Random-Forest.pickle", "wb") as f:
    pickle.dump(models[2][1], f)